<div class="content" id="content">
    <div class="artists">
        <?php foreach($artists as $member): ?>
            <div class="artist">
                <div class="pfp">
                    <img src="/resources/img/<?= $member->pfp ?>" alt="">
                </div>
                <div class="name">
                    <h3><?= $member->name  ?></h3>
                </div>
                <p>age: <?= $member->age?></p>
                <a href="/artists/id/<?= $member->id ?>">find out more</a>
            </div>
        <?php endforeach; ?>
    
    </div>
    
</div>