<?php

$artist = \Members\Artist::id($id);

$artist->getMusic();

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/resources/css/master.css">
    <title>Music</title>
</head>
<body>
    <?php require_once "includes/navbar.php"; ?>
    <div class="content" id="content">
        <div class="artist">
            <div class="pfp">
                <img src="/resources/img/<?= $artist->pfp ?>" alt="">
            </div>
            <div class="name">
                <h3><?= $artist->name  ?></h3>
            </div>
            <p>age: <?= $artist->age?></p>
            <a href="#">find out more</a>
        </div>
        <?php foreach($artist->music as $music): ?>
            <?php if($music->authorId == $artist->id): ?>
                <h1><?= $music->title ?></h1>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</body>
</html>