<?php
$studio = new Studio();

$studio->getArtists();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/resources/css/master.css">
    <title>Music</title>
</head>
<body>
    <?php require_once "includes/navbar.php"; ?>
    <div class="content" id="content">
        <div class="artists">
            <?php foreach($studio->artists as $member): ?>
                <div class="artist">
                    <div class="pfp">
                        <img src="/resources/img/<?= $member->pfp ?>" alt="">
                    </div>
                    <div class="name">
                        <h3><?= $member->name  ?></h3>
                    </div>
                    <p>age: <?= $member->age?></p>
                    <a href="/artists/id/<?= $member->id ?>">find out more</a>
                </div>
            <?php endforeach; ?>
        
        </div>
        
    </div>
</body>
</html>