<div class="content" id="content">
    <div class="artist">
        <div class="pfp">
            <img src="/resources/img/<?= $artist->pfp ?>" alt="">
        </div>
        <div class="name">
            <h3><?= $artist->name  ?></h3>
        </div>
        <p>age: <?= $artist->age?></p>
        <a href="#">find out more</a>
    </div>
    <?php foreach($bands as $band): ?>
        <h1><?= $band->name ?></h1>
        <ul>
            <?php foreach($band->getAlbums() as $album): ?>
               <li><?= $album->title; ?></li>
               <ul>
                   <?php foreach($album->getMusic() as $music): ?>
                       <li><?= $music->title; ?></li>
                   <?php endforeach; ?>
               </ul>
            <?php endforeach; ?>
        </ul>
    <?php endforeach; ?>
</div>
