<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/resources/css/master.css">
    <title>Music</title>
</head>
<body>
    <?php require_once "includes/navbar.php"; ?>
    <div class="content" id="content">
        <form action="" method="post">
            hello
        </form>
    </div>
</body>
</html>