<div class="content" style="background-image: url('/resources/img/bg.png');">
    <div class="row">
        <section class="left">
            <div class="name">
                <h1>INNATE <br>STUDIOS</h1>
                <p>Feel the <b>rythm</b> flow</p>
            </div>
        </section>
        <section class="right">
            
            <div class="content-right">
                <h1>NEWS</h1>
                <div class="news">
                    <div style="background-image: url('/resources/img/news.png');" class="post">
                        <div class="cover">
                            <div class="bottom">
                                <h3>NEW SONG</h3>
                                <div class="bottom-inner">
                                    <p>by <span>Pearl Tongue</span></p>
                                    <div class="date">
                                        26/04/2022
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div style="background-image: url('/resources/img/news1.png');" class="post">
                        <div class="cover">
                            <div class="bottom">
                                <h3>NEW SONG</h3>
                                <div class="bottom-inner">
                                    <div class="date">
                                        26/04/2022
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div style="background-image: url('/resources/img/news2.png');" class="post">
                        <div class="cover">
                            <div class="bottom">
                                <h3>NEW SONG</h3>
                                <div class="bottom-inner">
                                    <div class="date">
                                        26/04/2022
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>

                <div class="music">
                    <div class="bar-music"></div>
                    <ul>
                        <li class="music-selected"><div class="title">Save Yourself (Bonus Track)</div><div class="time">05:22</div></li>
                        <li><div class="title">Save Yourself (Bonus Track)</div><div class="time">05:22</div></li>
                        <li><div class="title">Save Yourself (Bonus Track)</div><div class="time">05:22</div></li>
                        <li><div class="title">Save Yourself (Bonus Track)</div><div class="time">05:22</div></li>
                        <li><div class="title">Save Yourself (Bonus Track)</div><div class="time">05:22</div></li>
                        <li><div class="title">Save Yourself (Bonus Track)</div><div class="time">05:22</div></li>
                        <li><div class="title">Save Yourself (Bonus Track)</div><div class="time">05:22</div></li>
                        <li><div class="title">Save Yourself (Bonus Track)</div><div class="time">05:22</div></li>
                        <li><div class="title">Save Yourself (Bonus Track)</div><div class="time">05:22</div></li>
                    </ul>
                    <div class="player">
                        <div class="progress-bar">
                            <div class="bar"></div>
                        </div>
                        <div class="play">
                            <img src="img/pause.png" alt="">
                        </div>
                    </div>
                </div>
            </div>
            <div class="back-text">
                <div class="scroll-text">
                    <h1>Save Yourself</h1>
                </div>
            </div>
        </section>
    </div>
</div>
