<div class="login">
    <form action="/login/authenticate" method="POST">
        <h1>Login</h1>
        <?= isset($error) ? $error : "" ?>
        <div class="field">
            <label for="email">Email:</label>
            <input type="email" name="email" id="email" placeholder="insert your email">
        </div>
        <div class="field">
            <label for="password">Password:</label>
            <input type="password" name="password" id="password" placeholder="insert your password">
        </div>
        <div class="field">
            <input type="submit" name="submit" value="Login">
        </div>
    </form>
</div>