<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <link rel="stylesheet" href="/resources/css/dashboard.css">
    <title>Music</title>
</head>
<body>
    <nav>
        <div class="logo">
            <img src="/resources/img/logo.png" alt="logo">
        </div>
        <ul>
            <li><a href="/dashboard"> <i class="fa fa-bar-chart"></i> <span>Metrics</span> </a></li>
            <li><a href="/dashboard-music"> <i class="fa fa-music"></i> <span>My Music</span> </a></li>
            <li><a href="/artists"> <i class="fa fa-users"></i> <span>Partners</span> </a></li>
            <li><a id="exit" href="/logout"> <i class="fas fa-sign-out-alt"></i> <span>Log out</span> </a></li>
        </ul>
    </nav>
    <div class="content">
        {{content}}
    </div>
</body>
</html>