<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <link rel="stylesheet" href="/resources/css/master.css">
    <title>Document</title>
</head>
<body>
    <nav>
        <div class="logo">
            INNATE STUDIOS
        </div>
        <ul>
            <li><a href="/">HOME</a></li>
            <li><a href="/artists">ARTISTS</a></li>
            <li><a href="/music">MUSIC</a></li>
            <li><a href="/bands">BANDS</a></li>
            <li><a href="/contact-us">CONTACT US</a></li>
            <?php if(isset($_SESSION['id'])): ?>
                <li><a href="/dashboard">DASHBOARD</a></li>
            <?php else: ?>
                <li><a href="/login">LOGIN</a></li>
            <?php endif; ?>
        </ul>
    </nav>
    {{content}}
    
    <footer>
        <div class="row">
            <div class="col-4">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eleifend tortor leo, sed pulvinar odio tincidunt in. Nam nec justo sapien. Donec porttitor est at venenatis imperdiet. Suspendisse sit amet urna placerat, blandit sem vel, porttitor metus. Ut dapibus quam vel finibus ultricies. Maecenas nec dapibus purus. Nulla lectus tellus, maximus vitae nulla at, condimentum consectetur leo. Fusce quis nisi mauris. Praesent nec nisl volutpat, eleifend sem dapibus, tincidunt risus.
            </div>
            <div class="col-4">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eleifend tortor leo, sed pulvinar odio tincidunt in. Nam nec justo sapien. Donec porttitor est at venenatis imperdiet. Suspendisse sit amet urna placerat, blandit sem vel, porttitor metus. Ut dapibus quam vel finibus ultricies. Maecenas nec dapibus purus. Nulla lectus tellus, maximus vitae nulla at, condimentum consectetur leo. Fusce quis nisi mauris. Praesent nec nisl volutpat, eleifend sem dapibus, tincidunt risus.
            </div>
            <div class="col-4">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eleifend tortor leo, sed pulvinar odio tincidunt in. Nam nec justo sapien. Donec porttitor est at venenatis imperdiet. Suspendisse sit amet urna placerat, blandit sem vel, porttitor metus. Ut dapibus quam vel finibus ultricies. Maecenas nec dapibus purus. Nulla lectus tellus, maximus vitae nulla at, condimentum consectetur leo. Fusce quis nisi mauris. Praesent nec nisl volutpat, eleifend sem dapibus, tincidunt risus.
            </div>
        </div>
    </footer>
    <script src="/resources/js/Music.js"></script>
    <script src="/resources/js/Player.js"></script>
    <script src="/resources/js/main.js"></script>
</body>
</html>